"""Guides added for search traffic on 2026-10-09 (owner: "3-4 new guides for common questions, in 8 languages").

Merged into guides.GUIDES (they come after the three showcase guides). Facts used here are the site's own:
Workshop rows 630/640/750/800 px cut in five (150 px parts by default), Featured 630 px, Artwork 506 + 100 px,
Workshop squares 150 x 150, the 5 MB limit and the HEX 21 ending (processor.py), Workshop items shown at about
122 px in Steam (showcase-builder.js STEAM_LAYOUT), fitted GIFs from the original frames (fit_frames_to_gif),
GIF Optimizer is Pro (beta), Loop is free once a week with an account, 5 files a day free without one.
``mode`` None = no showcase diagram; ``table`` = optional {"head": [...], "rows": [[...]]}.
"""
from __future__ import annotations

GUIDES_EXTRA: dict[str, dict[str, dict]] = {
    # ------------------------------------------------------------------ profile design (broad query)
    "steam-profile-design": {
        "en": {
            "title": "How to design your Steam profile: step by step",
            "description": "Background, showcases, animated GIFs and an info box: how to make a good-looking Steam profile in about 5 minutes.",
            "intro": "A Steam profile is a background, an avatar and the showcases under your name. It looks designed when these parts match: one picture running across the showcases, colours that fit the background. This is the order that works.",
            "mode": None,
            "steps": [
                ("Check your Steam level", "Showcases open at Steam level 10, and higher levels give more showcase slots. Below level 10 you can still change the background, avatar and frame."),
                ("Pick a background", "Profile backgrounds come from the Steam Points Shop or the Community Market; Steam does not let you upload your own. In “Create a design” you can browse Steam backgrounds and see them behind your showcase before buying."),
                ("Choose the showcase type", "Workshop shows five panels in a row, Featured Artwork one large picture, Artwork a large picture with a narrow side panel. Five Workshop panels cut from one picture give the widest single artwork."),
                ("Prepare the files", "Add a picture, GIF or video in Showcase Maker, choose the showcase and download the ZIP. Sizes, the 5 MB limit and the HEX 21 ending Steam needs are handled for you."),
                ("Check it on a profile mockup", "In the result window press “See it on a Steam profile”: your files appear inside a Steam profile template before you upload anything."),
                ("Upload and add the text", "Upload the files (the guides below show how, or use the extension), then fill the Custom Info Box: ready templates are in the “Info box” tab."),
            ],
            "faq": [
                ("Is it free?", "Yes. Preparing showcase files is free (5 files a day even without an account). Pro removes limits and the watermark from previews and adds extra tools."),
                ("Can I upload my own animated background or avatar?", "No, Steam sells them in the Points Shop. Animated showcases are the part of the profile you can make yourself."),
                ("I don't see the showcase section", "It appears at Steam level 10."),
            ],
        },
        "ru": {
            "title": "Как оформить профиль Steam: пошаговая инструкция",
            "description": "Фон, витрины, анимированные GIF и информационное поле: как красиво оформить профиль Steam примерно за 5 минут.",
            "intro": "Профиль Steam — это фон, аватар и витрины под ником. Оформленным он выглядит, когда всё сочетается: одна картинка проходит через витрины, цвета подходят к фону. Вот порядок, который работает.",
            "mode": None,
            "steps": [
                ("Проверь уровень Steam", "Витрины открываются на 10 уровне Steam, на более высоких уровнях их можно поставить больше. До 10 уровня можно менять фон, аватар и рамку."),
                ("Выбери фон", "Фоны профиля продаются в магазине очков Steam и на торговой площадке, свой загрузить нельзя. Во вкладке «Создать дизайн» можно перебрать фоны Steam и посмотреть их за своей витриной до покупки."),
                ("Выбери тип витрины", "Витрина мастерской — пять частей в ряд, избранная иллюстрация — одна большая картинка, витрина иллюстраций — большая картинка и узкая боковая полоса. Пять частей мастерской из одной картинки дают самую широкую иллюстрацию."),
                ("Подготовь файлы", "Добавь картинку, GIF или видео в Showcase Maker, выбери витрину и скачай ZIP. Размеры, лимит 5 МБ и нужный Steam последний байт (HEX 21) сайт сделает сам."),
                ("Проверь на макете профиля", "В окне результата нажми «Посмотреть на профиле»: файлы встанут в шаблон профиля Steam ещё до загрузки."),
                ("Загрузи и добавь текст", "Загрузи файлы (как — в инструкциях ниже или через расширение), затем заполни «Поле со своей информацией»: готовые шаблоны есть во вкладке «Инфо-поле»."),
            ],
            "faq": [
                ("Это бесплатно?", "Да. Подготовка файлов для витрин бесплатна (5 файлов в день даже без аккаунта). Pro снимает лимиты и водяной знак с превью и открывает дополнительные инструменты."),
                ("Можно загрузить свой анимированный фон или аватар?", "Нет, их продаёт Steam в магазине очков. Анимированные витрины — та часть профиля, которую можно сделать самому."),
                ("Не вижу раздел витрин", "Он появляется на 10 уровне Steam."),
            ],
        },
        "uk": {
            "title": "Як оформити профіль Steam: покрокова інструкція",
            "description": "Фон, вітрини, анімовані GIF та інформаційне поле: як гарно оформити профіль Steam приблизно за 5 хвилин.",
            "intro": "Профіль Steam — це фон, аватар і вітрини під ніком. Оформленим він виглядає, коли все поєднується: одна картинка проходить через вітрини, кольори пасують до фону. Ось порядок, що працює.",
            "mode": None,
            "steps": [
                ("Перевір рівень Steam", "Вітрини відкриваються на 10 рівні Steam, на вищих рівнях їх можна поставити більше. До 10 рівня можна змінювати фон, аватар і рамку."),
                ("Обери фон", "Фони профілю продаються в магазині очок Steam і на торговому майданчику, свій завантажити не можна. У вкладці «Створити дизайн» можна переглянути фони Steam за своєю вітриною ще до купівлі."),
                ("Обери тип вітрини", "Вітрина майстерні — п’ять частин у ряд, вибрана ілюстрація — одна велика картинка, вітрина ілюстрацій — велика картинка й вузька бічна смуга. П’ять частин майстерні з однієї картинки дають найширшу ілюстрацію."),
                ("Підготуй файли", "Додай картинку, GIF або відео в Showcase Maker, обери вітрину й завантаж ZIP. Розміри, ліміт 5 МБ і потрібний Steam останній байт (HEX 21) сайт зробить сам."),
                ("Перевір на макеті профілю", "У вікні результату натисни «Подивитися на профілі»: файли стануть у шаблон профілю Steam ще до завантаження."),
                ("Завантаж і додай текст", "Завантаж файли (як — в інструкціях нижче або через розширення), потім заповни «Поле зі своєю інформацією»: готові шаблони є у вкладці «Інфо-поле»."),
            ],
            "faq": [
                ("Це безкоштовно?", "Так. Підготовка файлів для вітрин безкоштовна (5 файлів на день навіть без акаунта). Pro знімає ліміти й водяний знак із превʼю та відкриває додаткові інструменти."),
                ("Чи можна завантажити свій анімований фон або аватар?", "Ні, їх продає Steam у магазині очок. Анімовані вітрини — та частина профілю, яку можна зробити самому."),
                ("Не бачу розділ вітрин", "Він з’являється на 10 рівні Steam."),
            ],
        },
        "de": {
            "title": "Steam-Profil gestalten: Schritt-für-Schritt-Anleitung",
            "description": "Hintergrund, Vitrinen, animierte GIFs und Infobox: So gestaltest du dein Steam-Profil in etwa 5 Minuten.",
            "intro": "Ein Steam-Profil besteht aus Hintergrund, Avatar und den Vitrinen unter deinem Namen. Gestaltet wirkt es, wenn alles zusammenpasst: ein Bild läuft durch die Vitrinen, die Farben passen zum Hintergrund. So gehst du vor.",
            "mode": None,
            "steps": [
                ("Steam-Level prüfen", "Vitrinen gibt es ab Steam-Level 10, höhere Level bringen weitere Plätze. Darunter kannst du Hintergrund, Avatar und Rahmen ändern."),
                ("Hintergrund wählen", "Profilhintergründe gibt es im Steam-Punkteshop oder auf dem Community-Markt; eigene kann man nicht hochladen. In „Design erstellen“ kannst du Steam-Hintergründe durchsehen und hinter deiner Vitrine ansehen, bevor du kaufst."),
                ("Vitrinentyp wählen", "Workshop zeigt fünf Teile nebeneinander, Featured Artwork ein großes Bild, Artwork ein großes Bild mit schmalem Seitenteil. Fünf Workshop-Teile aus einem Bild ergeben das breiteste Artwork."),
                ("Dateien vorbereiten", "Füge in Showcase Maker ein Bild, GIF oder Video hinzu, wähle die Vitrine und lade das ZIP herunter. Größen, das 5-MB-Limit und das von Steam benötigte letzte Byte (HEX 21) erledigt die Seite."),
                ("Auf dem Profil-Mockup prüfen", "Klicke im Ergebnisfenster auf „Im Steam-Profil ansehen“: Deine Dateien erscheinen in einer Steam-Profilvorlage, bevor du etwas hochlädst."),
                ("Hochladen und Text ergänzen", "Lade die Dateien hoch (wie, zeigen die Anleitungen unten, oder nutze die Erweiterung) und fülle die Infobox aus: fertige Vorlagen findest du im Tab „Infobox“."),
            ],
            "faq": [
                ("Ist das kostenlos?", "Ja. Vitrinendateien vorzubereiten ist kostenlos (5 Dateien pro Tag, sogar ohne Konto). Pro hebt Limits und das Wasserzeichen in Vorschauen auf und bringt weitere Werkzeuge."),
                ("Kann ich einen eigenen animierten Hintergrund oder Avatar hochladen?", "Nein, Steam verkauft sie im Punkteshop. Animierte Vitrinen sind der Teil des Profils, den du selbst gestalten kannst."),
                ("Ich sehe keinen Vitrinenbereich", "Er erscheint ab Steam-Level 10."),
            ],
        },
        "tr": {
            "title": "Steam profili nasıl tasarlanır: adım adım rehber",
            "description": "Arka plan, vitrinler, hareketli GIF’ler ve bilgi kutusu: Steam profilini yaklaşık 5 dakikada güzelce düzenle.",
            "intro": "Steam profili; arka plan, avatar ve adının altındaki vitrinlerden oluşur. Her şey uyumlu olduğunda tasarlanmış görünür: tek bir resim vitrinlerden geçer, renkler arka plana uyar. İşte işe yarayan sıra.",
            "mode": None,
            "steps": [
                ("Steam seviyeni kontrol et", "Vitrinler Steam seviyesi 10’da açılır, daha yüksek seviyeler daha fazla yer verir. 10’un altında arka planı, avatarı ve çerçeveyi değiştirebilirsin."),
                ("Arka plan seç", "Profil arka planları Steam Puan Dükkânı’nda veya Topluluk Pazarı’nda satılır; kendi arka planını yükleyemezsin. “Tasarım oluştur” sekmesinde Steam arka planlarına göz atıp satın almadan önce vitrininin arkasında görebilirsin."),
                ("Vitrin türünü seç", "Atölye beş parçayı yan yana gösterir, Featured Artwork tek büyük resmi, Artwork büyük resmi ve dar bir yan paneli. Tek resimden kesilen beş Atölye parçası en geniş çizimi verir."),
                ("Dosyaları hazırla", "Showcase Maker’a resim, GIF veya video ekle, vitrini seç ve ZIP’i indir. Boyutlar, 5 MB sınırı ve Steam’in istediği son bayt (HEX 21) otomatik halledilir."),
                ("Profil maketinde kontrol et", "Sonuç penceresinde “Steam profilinde gör”e bas: dosyaların, hiçbir şey yüklemeden önce bir Steam profil şablonunda görünür."),
                ("Yükle ve metni ekle", "Dosyaları yükle (nasıl olduğu aşağıdaki rehberlerde ya da eklentiyle), sonra Özel Bilgi Kutusu’nu doldur: hazır şablonlar “Bilgi kutusu” sekmesinde."),
            ],
            "faq": [
                ("Ücretsiz mi?", "Evet. Vitrin dosyalarını hazırlamak ücretsizdir (hesap olmadan bile günde 5 dosya). Pro sınırları ve önizlemelerdeki filigranı kaldırır, ek araçlar açar."),
                ("Kendi hareketli arka planımı veya avatarımı yükleyebilir miyim?", "Hayır, Steam bunları Puan Dükkânı’nda satar. Hareketli vitrinler profilin kendin yapabileceğin kısmıdır."),
                ("Vitrin bölümünü göremiyorum", "Steam seviyesi 10’da görünür."),
            ],
        },
        "fr": {
            "title": "Comment personnaliser son profil Steam : pas à pas",
            "description": "Arrière-plan, vitrines, GIF animés et boîte d’infos : comment rendre votre profil Steam beau en 5 minutes environ.",
            "intro": "Un profil Steam, c’est un arrière-plan, un avatar et les vitrines sous votre nom. Il paraît travaillé quand tout s’accorde : une image qui traverse les vitrines, des couleurs assorties à l’arrière-plan. Voici l’ordre qui marche.",
            "mode": None,
            "steps": [
                ("Vérifier votre niveau Steam", "Les vitrines s’ouvrent au niveau Steam 10, et les niveaux supérieurs donnent plus d’emplacements. Avant, vous pouvez changer l’arrière-plan, l’avatar et le cadre."),
                ("Choisir un arrière-plan", "Les arrière-plans de profil se trouvent dans la boutique de points Steam ou sur le marché de la communauté ; Steam ne permet pas d’envoyer le vôtre. Dans « Créer un design », parcourez les arrière-plans Steam et voyez-les derrière votre vitrine avant d’acheter."),
                ("Choisir le type de vitrine", "Workshop affiche cinq panneaux côte à côte, Featured Artwork une grande image, Artwork une grande image avec un panneau latéral étroit. Cinq panneaux Workshop tirés d’une image donnent l’illustration la plus large."),
                ("Préparer les fichiers", "Ajoutez une image, un GIF ou une vidéo dans Showcase Maker, choisissez la vitrine et téléchargez le ZIP. Les tailles, la limite de 5 Mo et le dernier octet exigé par Steam (HEX 21) sont gérés pour vous."),
                ("Vérifier sur une maquette de profil", "Dans la fenêtre du résultat, cliquez sur « Voir sur un profil Steam » : vos fichiers apparaissent dans un modèle de profil Steam avant tout envoi."),
                ("Envoyer et ajouter le texte", "Envoyez les fichiers (les guides ci-dessous expliquent comment, ou utilisez l’extension), puis remplissez la boîte d’infos personnalisée : des modèles prêts sont dans l’onglet « Boîte d’infos »."),
            ],
            "faq": [
                ("C’est gratuit ?", "Oui. Préparer les fichiers de vitrine est gratuit (5 fichiers par jour, même sans compte). Pro lève les limites et le filigrane des aperçus et ajoute des outils."),
                ("Puis-je envoyer mon propre arrière-plan ou avatar animé ?", "Non, Steam les vend dans la boutique de points. Les vitrines animées sont la partie du profil que vous pouvez créer vous-même."),
                ("Je ne vois pas la section des vitrines", "Elle apparaît au niveau Steam 10."),
            ],
        },
        "es": {
            "title": "Cómo decorar tu perfil de Steam: paso a paso",
            "description": "Fondo, escaparates, GIF animados y cuadro de información: cómo dejar bonito tu perfil de Steam en unos 5 minutos.",
            "intro": "Un perfil de Steam es un fondo, un avatar y los escaparates bajo tu nombre. Se ve diseñado cuando todo combina: una imagen que recorre los escaparates y colores que van con el fondo. Este es el orden que funciona.",
            "mode": None,
            "steps": [
                ("Revisa tu nivel de Steam", "Los escaparates se abren en el nivel 10 de Steam y los niveles superiores dan más huecos. Antes puedes cambiar el fondo, el avatar y el marco."),
                ("Elige un fondo", "Los fondos de perfil se consiguen en la tienda de puntos de Steam o en el mercado de la comunidad; Steam no permite subir uno propio. En «Crear un diseño» puedes ver fondos de Steam detrás de tu escaparate antes de comprar."),
                ("Elige el tipo de escaparate", "Workshop muestra cinco paneles en fila, Featured Artwork una imagen grande y Artwork una imagen grande con un panel lateral estrecho. Cinco paneles de Workshop de una misma imagen dan la ilustración más ancha."),
                ("Prepara los archivos", "Añade una imagen, GIF o vídeo en Showcase Maker, elige el escaparate y descarga el ZIP. Los tamaños, el límite de 5 MB y el último byte que pide Steam (HEX 21) se hacen solos."),
                ("Compruébalo en una maqueta del perfil", "En la ventana del resultado pulsa «Ver en un perfil de Steam»: tus archivos aparecen en una plantilla de perfil antes de subir nada."),
                ("Sube y añade el texto", "Sube los archivos (las guías de abajo explican cómo, o usa la extensión) y rellena el cuadro de información: hay plantillas listas en la pestaña «Cuadro de info»."),
            ],
            "faq": [
                ("¿Es gratis?", "Sí. Preparar archivos de escaparate es gratis (5 archivos al día incluso sin cuenta). Pro quita los límites y la marca de agua de las vistas previas y añade herramientas."),
                ("¿Puedo subir mi propio fondo o avatar animado?", "No, Steam los vende en la tienda de puntos. Los escaparates animados son la parte del perfil que puedes hacer tú."),
                ("No veo la sección de escaparates", "Aparece en el nivel 10 de Steam."),
            ],
        },
        "pt": {
            "title": "Como personalizar seu perfil Steam: passo a passo",
            "description": "Fundo, vitrines, GIFs animados e caixa de informações: como deixar seu perfil Steam bonito em cerca de 5 minutos.",
            "intro": "Um perfil Steam é um fundo, um avatar e as vitrines abaixo do seu nome. Ele parece caprichado quando tudo combina: uma imagem que atravessa as vitrines e cores que combinam com o fundo. Esta é a ordem que funciona.",
            "mode": None,
            "steps": [
                ("Confira seu nível na Steam", "As vitrines liberam no nível 10 da Steam, e níveis maiores dão mais espaços. Antes disso você pode trocar fundo, avatar e moldura."),
                ("Escolha um fundo", "Fundos de perfil vêm da Loja de Pontos da Steam ou do Mercado da Comunidade; a Steam não deixa enviar um próprio. Em «Criar um design» você vê fundos da Steam atrás da sua vitrine antes de comprar."),
                ("Escolha o tipo de vitrine", "Oficina mostra cinco partes lado a lado, Featured Artwork uma imagem grande e Artwork uma imagem grande com um painel lateral estreito. Cinco partes da Oficina tiradas de uma imagem formam a ilustração mais larga."),
                ("Prepare os arquivos", "Adicione uma imagem, GIF ou vídeo no Showcase Maker, escolha a vitrine e baixe o ZIP. Tamanhos, o limite de 5 MB e o último byte exigido pela Steam (HEX 21) são resolvidos para você."),
                ("Confira numa maquete do perfil", "Na janela do resultado clique em «Ver em um perfil Steam»: seus arquivos aparecem num modelo de perfil antes de enviar qualquer coisa."),
                ("Envie e adicione o texto", "Envie os arquivos (os guias abaixo mostram como, ou use a extensão) e preencha a caixa de informações: há modelos prontos na aba «Caixa de info»."),
            ],
            "faq": [
                ("É grátis?", "Sim. Preparar arquivos de vitrine é grátis (5 arquivos por dia, mesmo sem conta). O Pro tira os limites e a marca d’água das prévias e libera mais ferramentas."),
                ("Posso enviar meu próprio fundo ou avatar animado?", "Não, a Steam vende esses itens na Loja de Pontos. Vitrines animadas são a parte do perfil que você mesmo pode fazer."),
                ("Não vejo a seção de vitrines", "Ela aparece no nível 10 da Steam."),
            ],
        },
    },
    # ------------------------------------------------------------------ sizes
    "steam-showcase-sizes": {
        "en": {
            "title": "Steam showcase sizes: Workshop, Featured and Artwork (px, MB)",
            "description": "Exact image sizes for Steam profile showcases: Workshop 5 parts, Featured Artwork 630 px, Artwork 506 + 100 px and the 5 MB limit.",
            "intro": "Steam does not publish these numbers: they follow from how the profile page lays showcases out. Files of another width get scaled, and parts cut from one picture stop meeting at the edges.",
            "mode": None,
            "table": {"head": ["Showcase", "Files", "Width of each file", "Height", "Limit"], "rows": [
                ["Workshop", "5", "150 px (a 750 px picture cut in five; Steam shows each at about 122 px)", "any — tall files make a long showcase", "5 MB each"],
                ["Featured Artwork", "1", "630 px", "any", "5 MB"],
                ["Artwork with a side panel", "2", "506 px + 100 px", "the same for both", "5 MB each"],
                ["Workshop squares", "5", "150 × 150 px", "150 px", "5 MB each"],
            ]},
            "steps": [
                ("Choose the showcase", "Decide where the picture goes: five Workshop panels, one Featured Artwork or Artwork with a side panel."),
                ("Get files of the exact size", "Add any picture, GIF or video to Showcase Maker and pick the showcase type. It scales, cuts and names the files to the sizes in the table."),
                ("Check the cut on the preview", "The preview shows the parts with the same gaps Steam leaves between them, so you see what lands on each edge."),
            ],
            "faq": [
                ("My picture has another size", "That is fine: the site scales it to the showcase width, and you choose the visible area."),
                ("Does the height matter?", "Steam keeps the height of the files, so a tall picture makes a long showcase. For animations the 5 MB limit is what limits the height."),
                ("Why exactly 5 MB?", "It is the largest artwork file Steam accepts. Showcase Maker fits every finished GIF under it."),
            ],
        },
        "ru": {
            "title": "Размеры витрин Steam: мастерская, иллюстрации и избранное (px, МБ)",
            "description": "Точные размеры картинок для витрин профиля Steam: мастерская 5 частей, избранная иллюстрация 630 px, иллюстрации 506 + 100 px и лимит 5 МБ.",
            "intro": "Steam не публикует эти числа: они следуют из того, как страница профиля раскладывает витрины. Файлы другой ширины Steam масштабирует, и части одной картинки перестают совпадать по краям.",
            "mode": None,
            "table": {"head": ["Витрина", "Файлов", "Ширина каждого файла", "Высота", "Лимит"], "rows": [
                ["Витрина мастерской", "5", "150 px (картинка 750 px на пять частей; Steam показывает каждую примерно в 122 px)", "любая — высокие файлы дают длинную витрину", "5 МБ каждый"],
                ["Избранная иллюстрация", "1", "630 px", "любая", "5 МБ"],
                ["Витрина иллюстраций с боковой частью", "2", "506 px + 100 px", "одинаковая у обеих", "5 МБ каждый"],
                ["Квадраты в мастерской", "5", "150 × 150 px", "150 px", "5 МБ каждый"],
            ]},
            "steps": [
                ("Выбери витрину", "Реши, куда пойдёт картинка: пять частей мастерской, одна избранная иллюстрация или витрина иллюстраций с боковой частью."),
                ("Получи файлы точного размера", "Добавь любую картинку, GIF или видео в Showcase Maker и выбери тип витрины. Сайт сам масштабирует, нарежет и назовёт файлы по размерам из таблицы."),
                ("Проверь разрез на превью", "Предпросмотр показывает части с теми же промежутками, что оставляет Steam, — видно, что окажется на каждом краю."),
            ],
            "faq": [
                ("У моей картинки другой размер", "Ничего страшного: сайт приведёт её к ширине витрины, а видимую область выберешь ты."),
                ("Важна ли высота?", "Steam сохраняет высоту файлов, поэтому высокая картинка даёт длинную витрину. Для анимации высоту ограничивает лимит 5 МБ."),
                ("Почему именно 5 МБ?", "Это максимальный размер иллюстрации, который принимает Steam. Showcase Maker укладывает в него каждый готовый GIF."),
            ],
        },
        "uk": {
            "title": "Розміри вітрин Steam: майстерня, ілюстрації та обране (px, МБ)",
            "description": "Точні розміри картинок для вітрин профілю Steam: майстерня 5 частин, вибрана ілюстрація 630 px, ілюстрації 506 + 100 px і ліміт 5 МБ.",
            "intro": "Steam не публікує цих чисел: вони випливають із того, як сторінка профілю розкладає вітрини. Файли іншої ширини Steam масштабує, і частини однієї картинки перестають збігатися по краях.",
            "mode": None,
            "table": {"head": ["Вітрина", "Файлів", "Ширина кожного файла", "Висота", "Ліміт"], "rows": [
                ["Вітрина майстерні", "5", "150 px (картинка 750 px на п’ять частин; Steam показує кожну приблизно в 122 px)", "будь-яка — високі файли дають довгу вітрину", "5 МБ кожен"],
                ["Вибрана ілюстрація", "1", "630 px", "будь-яка", "5 МБ"],
                ["Вітрина ілюстрацій з бічною частиною", "2", "506 px + 100 px", "однакова в обох", "5 МБ кожен"],
                ["Квадрати в майстерні", "5", "150 × 150 px", "150 px", "5 МБ кожен"],
            ]},
            "steps": [
                ("Обери вітрину", "Виріши, куди піде картинка: п’ять частин майстерні, одна вибрана ілюстрація чи вітрина ілюстрацій із бічною частиною."),
                ("Отримай файли точного розміру", "Додай будь-яку картинку, GIF або відео в Showcase Maker і обери тип вітрини. Сайт сам масштабує, наріже й назве файли за розмірами з таблиці."),
                ("Перевір розріз на превʼю", "Попередній перегляд показує частини з тими ж проміжками, що залишає Steam, — видно, що опиниться на кожному краї."),
            ],
            "faq": [
                ("У моєї картинки інший розмір", "Нічого страшного: сайт приведе її до ширини вітрини, а видиму область обереш ти."),
                ("Чи важлива висота?", "Steam зберігає висоту файлів, тож висока картинка дає довгу вітрину. Для анімації висоту обмежує ліміт 5 МБ."),
                ("Чому саме 5 МБ?", "Це найбільший розмір ілюстрації, який приймає Steam. Showcase Maker вкладає в нього кожен готовий GIF."),
            ],
        },
        "de": {
            "title": "Steam-Vitrinengrößen: Workshop, Featured und Artwork (px, MB)",
            "description": "Genaue Bildgrößen für Steam-Profilvitrinen: Workshop 5 Teile, Featured Artwork 630 px, Artwork 506 + 100 px und das 5-MB-Limit.",
            "intro": "Steam veröffentlicht diese Zahlen nicht: Sie ergeben sich daraus, wie die Profilseite die Vitrinen anordnet. Dateien mit anderer Breite werden skaliert, und Teile eines Bildes treffen an den Kanten nicht mehr zusammen.",
            "mode": None,
            "table": {"head": ["Vitrine", "Dateien", "Breite jeder Datei", "Höhe", "Limit"], "rows": [
                ["Workshop", "5", "150 px (ein 750-px-Bild in fünf Teilen; Steam zeigt jedes mit etwa 122 px)", "beliebig — hohe Dateien ergeben eine lange Vitrine", "je 5 MB"],
                ["Featured Artwork", "1", "630 px", "beliebig", "5 MB"],
                ["Artwork mit Seitenteil", "2", "506 px + 100 px", "bei beiden gleich", "je 5 MB"],
                ["Workshop-Quadrate", "5", "150 × 150 px", "150 px", "je 5 MB"],
            ]},
            "steps": [
                ("Vitrine wählen", "Entscheide, wohin das Bild kommt: fünf Workshop-Teile, ein Featured Artwork oder Artwork mit Seitenteil."),
                ("Dateien in exakter Größe erhalten", "Füge ein beliebiges Bild, GIF oder Video in Showcase Maker hinzu und wähle den Vitrinentyp. Die Seite skaliert, schneidet und benennt die Dateien nach der Tabelle."),
                ("Schnitt in der Vorschau prüfen", "Die Vorschau zeigt die Teile mit denselben Lücken wie Steam – du siehst, was an jeder Kante landet."),
            ],
            "faq": [
                ("Mein Bild hat eine andere Größe", "Kein Problem: Die Seite bringt es auf die Vitrinenbreite, den sichtbaren Bereich wählst du."),
                ("Spielt die Höhe eine Rolle?", "Steam behält die Höhe der Dateien bei, ein hohes Bild ergibt also eine lange Vitrine. Bei Animationen begrenzt das 5-MB-Limit die Höhe."),
                ("Warum genau 5 MB?", "Das ist die größte Artwork-Datei, die Steam annimmt. Showcase Maker bringt jedes fertige GIF darunter."),
            ],
        },
        "tr": {
            "title": "Steam vitrin boyutları: Atölye, Featured ve Artwork (px, MB)",
            "description": "Steam profil vitrinleri için kesin resim boyutları: Atölye 5 parça, Featured Artwork 630 px, Artwork 506 + 100 px ve 5 MB sınırı.",
            "intro": "Steam bu sayıları yayınlamaz: profil sayfasının vitrinleri nasıl dizdiğinden çıkarlar. Başka genişlikteki dosyalar ölçeklenir ve tek resimden kesilen parçalar kenarlarda buluşmaz.",
            "mode": None,
            "table": {"head": ["Vitrin", "Dosya", "Her dosyanın genişliği", "Yükseklik", "Sınır"], "rows": [
                ["Atölye", "5", "150 px (750 px’lik resim beşe bölünür; Steam her birini yaklaşık 122 px gösterir)", "serbest — uzun dosyalar uzun vitrin yapar", "her biri 5 MB"],
                ["Featured Artwork", "1", "630 px", "serbest", "5 MB"],
                ["Yan panelli Artwork", "2", "506 px + 100 px", "ikisinde aynı", "her biri 5 MB"],
                ["Atölye kareleri", "5", "150 × 150 px", "150 px", "her biri 5 MB"],
            ]},
            "steps": [
                ("Vitrini seç", "Resmin nereye gideceğine karar ver: beş Atölye parçası, tek Featured Artwork ya da yan panelli Artwork."),
                ("Tam boyutta dosyalar al", "Showcase Maker’a herhangi bir resim, GIF veya video ekle ve vitrin türünü seç. Site dosyaları tablodaki boyutlara göre ölçekler, keser ve adlandırır."),
                ("Kesimi önizlemede kontrol et", "Önizleme parçaları Steam’in bıraktığı boşluklarla gösterir; her kenara ne düşeceğini görürsün."),
            ],
            "faq": [
                ("Resmimin boyutu farklı", "Sorun değil: site onu vitrin genişliğine getirir, görünen alanı sen seçersin."),
                ("Yükseklik önemli mi?", "Steam dosyaların yüksekliğini korur, yani uzun bir resim uzun bir vitrin yapar. Animasyonlarda yüksekliği 5 MB sınırı belirler."),
                ("Neden tam 5 MB?", "Steam’in kabul ettiği en büyük çizim dosyası bu. Showcase Maker her hazır GIF’i bunun altına sığdırır."),
            ],
        },
        "fr": {
            "title": "Tailles des vitrines Steam : Workshop, Featured et Artwork (px, Mo)",
            "description": "Tailles exactes des images pour les vitrines du profil Steam : Workshop 5 parties, Featured Artwork 630 px, Artwork 506 + 100 px et la limite de 5 Mo.",
            "intro": "Steam ne publie pas ces chiffres : ils découlent de la façon dont la page de profil dispose les vitrines. Les fichiers d’une autre largeur sont redimensionnés et les parties d’une même image ne se rejoignent plus.",
            "mode": None,
            "table": {"head": ["Vitrine", "Fichiers", "Largeur de chaque fichier", "Hauteur", "Limite"], "rows": [
                ["Workshop", "5", "150 px (une image de 750 px coupée en cinq ; Steam affiche chacune à environ 122 px)", "libre — les fichiers hauts donnent une vitrine longue", "5 Mo chacun"],
                ["Featured Artwork", "1", "630 px", "libre", "5 Mo"],
                ["Artwork avec panneau latéral", "2", "506 px + 100 px", "identique pour les deux", "5 Mo chacun"],
                ["Carrés Workshop", "5", "150 × 150 px", "150 px", "5 Mo chacun"],
            ]},
            "steps": [
                ("Choisir la vitrine", "Décidez où va l’image : cinq panneaux Workshop, une Featured Artwork ou un Artwork avec panneau latéral."),
                ("Obtenir des fichiers à la taille exacte", "Ajoutez une image, un GIF ou une vidéo dans Showcase Maker et choisissez le type de vitrine. Le site redimensionne, découpe et nomme les fichiers selon le tableau."),
                ("Vérifier la coupe dans l’aperçu", "L’aperçu montre les parties avec les mêmes espaces que Steam : vous voyez ce qui tombe sur chaque bord."),
            ],
            "faq": [
                ("Mon image a une autre taille", "Aucun souci : le site l’adapte à la largeur de la vitrine et vous choisissez la zone visible."),
                ("La hauteur compte-t-elle ?", "Steam garde la hauteur des fichiers, donc une image haute donne une vitrine longue. Pour les animations, c’est la limite de 5 Mo qui borne la hauteur."),
                ("Pourquoi 5 Mo exactement ?", "C’est le plus gros fichier d’illustration accepté par Steam. Showcase Maker fait passer chaque GIF terminé en dessous."),
            ],
        },
        "es": {
            "title": "Tamaños de escaparates de Steam: Workshop, Featured y Artwork (px, MB)",
            "description": "Tamaños exactos de imagen para los escaparates del perfil de Steam: Workshop 5 partes, Featured Artwork 630 px, Artwork 506 + 100 px y el límite de 5 MB.",
            "intro": "Steam no publica estos números: salen de cómo la página de perfil coloca los escaparates. Los archivos de otro ancho se escalan y las partes de una misma imagen dejan de coincidir en los bordes.",
            "mode": None,
            "table": {"head": ["Escaparate", "Archivos", "Ancho de cada archivo", "Alto", "Límite"], "rows": [
                ["Workshop", "5", "150 px (una imagen de 750 px cortada en cinco; Steam muestra cada una a unos 122 px)", "libre — los archivos altos hacen un escaparate largo", "5 MB cada uno"],
                ["Featured Artwork", "1", "630 px", "libre", "5 MB"],
                ["Artwork con panel lateral", "2", "506 px + 100 px", "igual en ambos", "5 MB cada uno"],
                ["Cuadrados de Workshop", "5", "150 × 150 px", "150 px", "5 MB cada uno"],
            ]},
            "steps": [
                ("Elige el escaparate", "Decide dónde va la imagen: cinco paneles de Workshop, un Featured Artwork o un Artwork con panel lateral."),
                ("Consigue archivos del tamaño exacto", "Añade cualquier imagen, GIF o vídeo a Showcase Maker y elige el tipo de escaparate. La web escala, corta y nombra los archivos según la tabla."),
                ("Revisa el corte en la vista previa", "La vista previa muestra las partes con los mismos huecos que deja Steam: ves qué queda en cada borde."),
            ],
            "faq": [
                ("Mi imagen tiene otro tamaño", "No pasa nada: la web la ajusta al ancho del escaparate y tú eliges la zona visible."),
                ("¿Importa la altura?", "Steam conserva la altura de los archivos, así que una imagen alta da un escaparate largo. En animaciones, la altura la limita el máximo de 5 MB."),
                ("¿Por qué justo 5 MB?", "Es el archivo de ilustración más grande que acepta Steam. Showcase Maker deja cada GIF terminado por debajo."),
            ],
        },
        "pt": {
            "title": "Tamanhos das vitrines da Steam: Oficina, Featured e Artwork (px, MB)",
            "description": "Tamanhos exatos de imagem para as vitrines do perfil Steam: Oficina 5 partes, Featured Artwork 630 px, Artwork 506 + 100 px e o limite de 5 MB.",
            "intro": "A Steam não publica esses números: eles vêm de como a página do perfil organiza as vitrines. Arquivos com outra largura são redimensionados e as partes de uma mesma imagem deixam de se encontrar nas bordas.",
            "mode": None,
            "table": {"head": ["Vitrine", "Arquivos", "Largura de cada arquivo", "Altura", "Limite"], "rows": [
                ["Oficina (Workshop)", "5", "150 px (uma imagem de 750 px cortada em cinco; a Steam mostra cada uma com cerca de 122 px)", "livre — arquivos altos fazem uma vitrine longa", "5 MB cada"],
                ["Featured Artwork", "1", "630 px", "livre", "5 MB"],
                ["Artwork com painel lateral", "2", "506 px + 100 px", "igual nas duas", "5 MB cada"],
                ["Quadrados da Oficina", "5", "150 × 150 px", "150 px", "5 MB cada"],
            ]},
            "steps": [
                ("Escolha a vitrine", "Decida onde a imagem vai: cinco partes da Oficina, uma Featured Artwork ou um Artwork com painel lateral."),
                ("Gere arquivos no tamanho exato", "Adicione qualquer imagem, GIF ou vídeo no Showcase Maker e escolha o tipo de vitrine. O site redimensiona, corta e nomeia os arquivos conforme a tabela."),
                ("Confira o corte na prévia", "A prévia mostra as partes com os mesmos espaços que a Steam deixa: você vê o que cai em cada borda."),
            ],
            "faq": [
                ("Minha imagem tem outro tamanho", "Tudo bem: o site ajusta à largura da vitrine e você escolhe a área visível."),
                ("A altura importa?", "A Steam mantém a altura dos arquivos, então uma imagem alta faz uma vitrine longa. Em animações, quem limita a altura é o máximo de 5 MB."),
                ("Por que exatamente 5 MB?", "É o maior arquivo de ilustração que a Steam aceita. O Showcase Maker deixa cada GIF pronto abaixo disso."),
            ],
        },
    },
    # ------------------------------------------------------------------ GIF over 5 MB
    "steam-gif-too-large": {
        "en": {
            "title": "GIF over 5 MB: why Steam won’t take it and how to shrink it",
            "description": "Steam artwork uploads stop at 5 MB. How to make a GIF smaller without ruining it: length, frame rate, width and colours.",
            "intro": "Steam does not accept artwork files over 5 MB, and GIFs grow fast because every frame is a whole picture. Usually a slightly shorter clip and a lower frame rate are enough.",
            "mode": None,
            "steps": [
                ("Let Showcase Maker fit it", "Add the GIF or video, choose the showcase type and create the files. Every finished GIF is fitted under 5 MB: the encoder looks for the best quality that still fits, starting from the original frames each time."),
                ("Shorten the clip", "Each second adds frames. A 3–6 second loop is plenty for a showcase. The “Loop” tool cuts a short piece of a video and makes the joint seamless."),
                ("Lower the frame rate", "15 frames per second looks smooth on a profile and is about half the size of 30. Set it under “Quality and format”."),
                ("Keep the width Steam shows", "A wider file than the showcase (630 px Featured, 506 + 100 px Artwork, 150 px per Workshop part) only adds weight. Tall GIFs for long showcases carry more pixels per frame, so give them fewer frames."),
                ("Compress a finished GIF", "If the GIF is already made, the “GIF Optimizer” tab reduces colours and adds lossy compression, with a before/after comparison (Pro)."),
            ],
            "faq": [
                ("Will the quality drop?", "A little: fewer colours or frames. Showcase Maker always starts from the original frames, so it never compresses an already compressed GIF again."),
                ("Steam rejects a GIF that is under 5 MB", "The upload trick also needs the file to end with a particular byte (HEX 21). Files from Showcase Maker already have it; GIFs from other editors often do not."),
                ("Do the five Workshop parts stay in sync?", "Yes. They are encoded as one group with the same frames, so they play together."),
            ],
        },
        "ru": {
            "title": "GIF больше 5 МБ: почему Steam не принимает и как уменьшить",
            "description": "Steam принимает иллюстрации до 5 МБ. Как уменьшить GIF и не испортить его: длина, частота кадров, ширина и цвета.",
            "intro": "Steam не принимает иллюстрации больше 5 МБ, а GIF растёт быстро: каждый кадр — целая картинка. Обычно хватает чуть укоротить ролик и снизить частоту кадров.",
            "mode": None,
            "steps": [
                ("Доверь подгонку Showcase Maker", "Добавь GIF или видео, выбери тип витрины и создай файлы. Каждый готовый GIF укладывается в 5 МБ: кодировщик ищет лучшее качество, которое ещё помещается, и каждый раз берёт исходные кадры."),
                ("Укороти ролик", "Каждая секунда добавляет кадры. Для витрины хватает петли 3–6 секунд. Инструмент «Зациклить» вырежет короткий кусок видео и сделает стык незаметным."),
                ("Снизь частоту кадров", "15 кадров в секунду смотрятся в профиле плавно и весят примерно вдвое меньше, чем 30. Это настраивается в «Качестве и формате»."),
                ("Держи ширину, которую показывает Steam", "Файл шире витрины (630 px избранная иллюстрация, 506 + 100 px иллюстрации, 150 px часть мастерской) только прибавляет вес. У высоких GIF для длинных витрин больше пикселей в кадре — им нужно меньше кадров."),
                ("Сожми готовый GIF", "Если GIF уже готов, вкладка «GIF оптимизатор» уменьшит число цветов и добавит сжатие с потерями, с сравнением «до и после» (Pro)."),
            ],
            "faq": [
                ("Качество упадёт?", "Немного: меньше цветов или кадров. Showcase Maker всегда начинает с исходных кадров и не сжимает уже сжатый GIF повторно."),
                ("Steam не принимает GIF меньше 5 МБ", "Для загрузки файл ещё должен заканчиваться определённым байтом (HEX 21). У файлов Showcase Maker он уже есть, у GIF из других редакторов часто нет."),
                ("Пять частей мастерской остаются синхронными?", "Да. Они кодируются одной группой с одинаковыми кадрами и играют вместе."),
            ],
        },
        "uk": {
            "title": "GIF більше 5 МБ: чому Steam не приймає і як зменшити",
            "description": "Steam приймає ілюстрації до 5 МБ. Як зменшити GIF і не зіпсувати його: довжина, частота кадрів, ширина й кольори.",
            "intro": "Steam не приймає ілюстрації понад 5 МБ, а GIF росте швидко: кожен кадр — ціла картинка. Зазвичай досить трохи вкоротити ролик і знизити частоту кадрів.",
            "mode": None,
            "steps": [
                ("Довір підгонку Showcase Maker", "Додай GIF або відео, обери тип вітрини й створи файли. Кожен готовий GIF вкладається в 5 МБ: кодувальник шукає найкращу якість, що ще вміщається, і щоразу бере вихідні кадри."),
                ("Вкороти ролик", "Кожна секунда додає кадри. Для вітрини досить петлі 3–6 секунд. Інструмент «Зациклити» виріже короткий шматок відео й зробить стик непомітним."),
                ("Знизь частоту кадрів", "15 кадрів на секунду виглядають у профілі плавно й важать приблизно вдвічі менше, ніж 30. Це налаштовується в «Якості та форматі»."),
                ("Тримай ширину, яку показує Steam", "Файл ширший за вітрину (630 px вибрана ілюстрація, 506 + 100 px ілюстрації, 150 px частина майстерні) лише додає вагу. У високих GIF для довгих вітрин більше пікселів у кадрі — їм потрібно менше кадрів."),
                ("Стисни готовий GIF", "Якщо GIF уже готовий, вкладка «GIF оптимізатор» зменшить кількість кольорів і додасть стиснення з втратами, з порівнянням «до і після» (Pro)."),
            ],
            "faq": [
                ("Якість впаде?", "Трохи: менше кольорів або кадрів. Showcase Maker завжди починає з вихідних кадрів і не стискає вже стиснений GIF удруге."),
                ("Steam не приймає GIF менше 5 МБ", "Для завантаження файл ще має закінчуватися певним байтом (HEX 21). У файлів Showcase Maker він уже є, у GIF з інших редакторів часто немає."),
                ("П’ять частин майстерні лишаються синхронними?", "Так. Вони кодуються однією групою з однаковими кадрами й грають разом."),
            ],
        },
        "de": {
            "title": "GIF über 5 MB: Warum Steam es ablehnt und wie es kleiner wird",
            "description": "Steam nimmt Artworks bis 5 MB an. So machst du ein GIF kleiner, ohne es zu ruinieren: Länge, Bildrate, Breite und Farben.",
            "intro": "Steam nimmt keine Artwork-Dateien über 5 MB an, und GIFs wachsen schnell, weil jedes Bild ein ganzes Bild ist. Meist reichen ein etwas kürzerer Clip und eine niedrigere Bildrate.",
            "mode": None,
            "steps": [
                ("Showcase Maker anpassen lassen", "Füge das GIF oder Video hinzu, wähle den Vitrinentyp und erstelle die Dateien. Jedes fertige GIF landet unter 5 MB: Der Encoder sucht die beste Qualität, die noch passt, und geht dabei immer von den Originalbildern aus."),
                ("Den Clip kürzen", "Jede Sekunde bringt Bilder dazu. Eine Schleife von 3–6 Sekunden reicht für eine Vitrine. Das Werkzeug „Loop“ schneidet ein kurzes Stück aus einem Video und macht den Übergang nahtlos."),
                ("Bildrate senken", "15 Bilder pro Sekunde wirken im Profil flüssig und sind etwa halb so groß wie 30. Einstellbar unter „Qualität und Format“."),
                ("Bei der Breite bleiben, die Steam zeigt", "Eine Datei breiter als die Vitrine (630 px Featured, 506 + 100 px Artwork, 150 px pro Workshop-Teil) macht sie nur schwerer. Hohe GIFs für lange Vitrinen haben mehr Pixel pro Bild und brauchen weniger Bilder."),
                ("Ein fertiges GIF komprimieren", "Ist das GIF schon fertig, reduziert der Tab „GIF-Optimierer“ die Farben und fügt verlustbehaftete Kompression hinzu, mit Vorher-Nachher-Vergleich (Pro)."),
            ],
            "faq": [
                ("Leidet die Qualität?", "Ein wenig: weniger Farben oder Bilder. Showcase Maker beginnt immer bei den Originalbildern und komprimiert kein schon komprimiertes GIF erneut."),
                ("Steam lehnt ein GIF unter 5 MB ab", "Für den Upload muss die Datei außerdem mit einem bestimmten Byte (HEX 21) enden. Dateien aus Showcase Maker haben es, GIFs aus anderen Editoren oft nicht."),
                ("Bleiben die fünf Workshop-Teile synchron?", "Ja. Sie werden als eine Gruppe mit denselben Bildern kodiert und laufen zusammen."),
            ],
        },
        "tr": {
            "title": "5 MB’tan büyük GIF: Steam neden kabul etmez, nasıl küçültülür",
            "description": "Steam çizim yüklemelerini 5 MB’ta keser. GIF’i bozmadan küçültmenin yolu: süre, kare hızı, genişlik ve renkler.",
            "intro": "Steam 5 MB’tan büyük çizim dosyalarını kabul etmez ve GIF’ler hızla büyür: her kare koca bir resimdir. Genelde klibi biraz kısaltmak ve kare hızını düşürmek yeter.",
            "mode": None,
            "steps": [
                ("Showcase Maker sığdırsın", "GIF’i veya videoyu ekle, vitrin türünü seç ve dosyaları oluştur. Her hazır GIF 5 MB’ın altına sığdırılır: kodlayıcı hâlâ sığan en iyi kaliteyi arar ve her seferinde orijinal karelerden başlar."),
                ("Klibi kısalt", "Her saniye kare ekler. Vitrin için 3–6 saniyelik döngü yeterli. “Döngü” aracı videodan kısa bir parça keser ve geçişi kusursuz yapar."),
                ("Kare hızını düşür", "Saniyede 15 kare profilde akıcı görünür ve 30’un yaklaşık yarısı kadar yer kaplar. “Kalite ve format” altında ayarlanır."),
                ("Steam’in gösterdiği genişlikte kal", "Vitrinden geniş bir dosya (Featured 630 px, Artwork 506 + 100 px, Atölye parçası 150 px) yalnızca ağırlık ekler. Uzun vitrinler için uzun GIF’lerde karede daha çok piksel vardır, onlara daha az kare ver."),
                ("Hazır GIF’i sıkıştır", "GIF zaten hazırsa “GIF Optimize Edici” sekmesi renkleri azaltır ve kayıplı sıkıştırma ekler; önce/sonra karşılaştırmasıyla (Pro)."),
            ],
            "faq": [
                ("Kalite düşer mi?", "Biraz: daha az renk veya kare. Showcase Maker her zaman orijinal karelerden başlar, sıkıştırılmış bir GIF’i yeniden sıkıştırmaz."),
                ("Steam 5 MB’tan küçük bir GIF’i reddediyor", "Yükleme için dosyanın belirli bir baytla (HEX 21) bitmesi de gerekir. Showcase Maker dosyalarında bu var, başka editörlerin GIF’lerinde çoğu zaman yok."),
                ("Beş Atölye parçası senkron kalır mı?", "Evet. Aynı karelerle tek grup olarak kodlanır ve birlikte oynarlar."),
            ],
        },
        "fr": {
            "title": "GIF de plus de 5 Mo : pourquoi Steam le refuse et comment le réduire",
            "description": "Steam limite les illustrations à 5 Mo. Comment réduire un GIF sans l’abîmer : durée, cadence, largeur et couleurs.",
            "intro": "Steam refuse les illustrations de plus de 5 Mo, et un GIF grossit vite : chaque image est une image complète. En général, un clip un peu plus court et une cadence plus basse suffisent.",
            "mode": None,
            "steps": [
                ("Laisser Showcase Maker l’ajuster", "Ajoutez le GIF ou la vidéo, choisissez le type de vitrine et créez les fichiers. Chaque GIF terminé passe sous 5 Mo : l’encodeur cherche la meilleure qualité qui tient encore, en repartant toujours des images d’origine."),
                ("Raccourcir le clip", "Chaque seconde ajoute des images. Une boucle de 3 à 6 secondes suffit pour une vitrine. L’outil « Loop » coupe un court extrait d’une vidéo et rend la jointure invisible."),
                ("Baisser la cadence", "15 images par seconde paraissent fluides sur un profil et pèsent environ moitié moins que 30. Réglage dans « Qualité et format »."),
                ("Garder la largeur affichée par Steam", "Un fichier plus large que la vitrine (630 px Featured, 506 + 100 px Artwork, 150 px par partie Workshop) ne fait qu’alourdir. Les GIF hauts des vitrines longues ont plus de pixels par image : donnez-leur moins d’images."),
                ("Compresser un GIF déjà fait", "Si le GIF est déjà prêt, l’onglet « Optimiseur GIF » réduit les couleurs et ajoute une compression avec perte, avec une comparaison avant/après (Pro)."),
            ],
            "faq": [
                ("La qualité va-t-elle baisser ?", "Un peu : moins de couleurs ou d’images. Showcase Maker repart toujours des images d’origine et ne recompresse jamais un GIF déjà compressé."),
                ("Steam refuse un GIF de moins de 5 Mo", "L’astuce d’envoi exige aussi que le fichier se termine par un octet précis (HEX 21). Les fichiers de Showcase Maker l’ont déjà, les GIF d’autres éditeurs souvent pas."),
                ("Les cinq parties Workshop restent-elles synchronisées ?", "Oui. Elles sont encodées en un seul groupe avec les mêmes images et défilent ensemble."),
            ],
        },
        "es": {
            "title": "GIF de más de 5 MB: por qué Steam no lo acepta y cómo reducirlo",
            "description": "Steam limita las ilustraciones a 5 MB. Cómo reducir un GIF sin estropearlo: duración, fotogramas por segundo, ancho y colores.",
            "intro": "Steam no acepta ilustraciones de más de 5 MB y un GIF crece rápido: cada fotograma es una imagen completa. Normalmente basta con acortar un poco el clip y bajar los fotogramas por segundo.",
            "mode": None,
            "steps": [
                ("Deja que Showcase Maker lo ajuste", "Añade el GIF o el vídeo, elige el tipo de escaparate y crea los archivos. Cada GIF terminado queda por debajo de 5 MB: el codificador busca la mejor calidad que todavía cabe, siempre a partir de los fotogramas originales."),
                ("Acorta el clip", "Cada segundo añade fotogramas. Para un escaparate basta un bucle de 3 a 6 segundos. La herramienta «Bucle» corta un trozo corto del vídeo y hace la unión invisible."),
                ("Baja los fotogramas por segundo", "15 fotogramas por segundo se ven fluidos en el perfil y pesan casi la mitad que 30. Se ajusta en «Calidad y formato»."),
                ("Usa el ancho que muestra Steam", "Un archivo más ancho que el escaparate (630 px Featured, 506 + 100 px Artwork, 150 px por parte de Workshop) solo añade peso. Los GIF altos de escaparates largos tienen más píxeles por fotograma: dales menos fotogramas."),
                ("Comprime un GIF ya hecho", "Si el GIF ya está hecho, la pestaña «Optimizador de GIF» reduce colores y añade compresión con pérdida, con comparación antes y después (Pro)."),
            ],
            "faq": [
                ("¿Bajará la calidad?", "Un poco: menos colores o fotogramas. Showcase Maker siempre parte de los fotogramas originales y nunca vuelve a comprimir un GIF ya comprimido."),
                ("Steam rechaza un GIF de menos de 5 MB", "El truco de subida también exige que el archivo termine en un byte concreto (HEX 21). Los archivos de Showcase Maker ya lo tienen; los GIF de otros editores muchas veces no."),
                ("¿Las cinco partes de Workshop siguen sincronizadas?", "Sí. Se codifican como un grupo con los mismos fotogramas y se reproducen a la vez."),
            ],
        },
        "pt": {
            "title": "GIF acima de 5 MB: por que a Steam recusa e como diminuir",
            "description": "A Steam limita as ilustrações a 5 MB. Como diminuir um GIF sem estragar: duração, quadros por segundo, largura e cores.",
            "intro": "A Steam não aceita ilustrações acima de 5 MB, e um GIF cresce rápido: cada quadro é uma imagem inteira. Normalmente basta encurtar um pouco o clipe e baixar os quadros por segundo.",
            "mode": None,
            "steps": [
                ("Deixe o Showcase Maker ajustar", "Adicione o GIF ou vídeo, escolha o tipo de vitrine e crie os arquivos. Cada GIF pronto fica abaixo de 5 MB: o codificador busca a melhor qualidade que ainda cabe, sempre a partir dos quadros originais."),
                ("Encurte o clipe", "Cada segundo adiciona quadros. Um loop de 3 a 6 segundos basta para uma vitrine. A ferramenta «Loop» corta um trecho curto do vídeo e deixa a emenda invisível."),
                ("Baixe os quadros por segundo", "15 quadros por segundo ficam suaves no perfil e pesam cerca de metade de 30. Ajuste em «Qualidade e formato»."),
                ("Use a largura que a Steam mostra", "Um arquivo mais largo que a vitrine (630 px Featured, 506 + 100 px Artwork, 150 px por parte da Oficina) só pesa mais. GIFs altos de vitrines longas têm mais pixels por quadro: dê menos quadros a eles."),
                ("Comprima um GIF pronto", "Se o GIF já está pronto, a aba «Otimizador de GIF» reduz as cores e aplica compressão com perdas, com comparação antes e depois (Pro)."),
            ],
            "faq": [
                ("A qualidade vai cair?", "Um pouco: menos cores ou quadros. O Showcase Maker sempre parte dos quadros originais e nunca recomprime um GIF já comprimido."),
                ("A Steam recusa um GIF abaixo de 5 MB", "O truque de envio também exige que o arquivo termine com um byte específico (HEX 21). Os arquivos do Showcase Maker já têm; GIFs de outros editores muitas vezes não."),
                ("As cinco partes da Oficina ficam sincronizadas?", "Sim. Elas são codificadas como um grupo com os mesmos quadros e tocam juntas."),
            ],
        },
    },
    # ------------------------------------------------------------------ long Workshop showcase
    "steam-long-workshop-showcase": {
        "en": {
            "title": "How to make a long Steam Workshop showcase",
            "description": "A tall picture cut into five Workshop parts makes a long showcase on your Steam profile. Sizes, limits and steps.",
            "intro": "Steam keeps the height of Workshop items. Cut a tall picture into five columns, and your profile gets one long artwork running down the page instead of a short strip.",
            "mode": "workshop",
            "steps": [
                ("Pick a tall picture", "Portrait art works best, for example 750 × 2000 px. The taller the picture, the longer the showcase; the 5 MB limit per part is the only ceiling."),
                ("Cut it into five parts", "In Showcase Maker choose “Workshop” and press “Create Steam files”. Every part is a fifth of the width and keeps the full height of the picture."),
                ("Watch animated parts", "A tall GIF has many pixels in every frame. Each part is fitted under 5 MB automatically; a short loop at 12–15 frames per second keeps the quality high."),
                ("Upload part_1 … part_5 in order", "Upload the files one by one as Workshop items: the console code from the Steam tab, or the SteamShowcase Helper extension."),
                ("Add them to the showcase", "Edit Profile → Showcase → “Workshop Showcase”, then select the five items in the same order."),
            ],
            "faq": [
                ("The parts are shifted or in the wrong order", "Select them strictly in order, part_1 first. All parts have the same height, so they only line up as one row."),
                ("Can I make the picture wider instead?", "The width is fixed by Steam: about 630 px for the whole row. Long showcases grow only downward."),
                ("I have no showcases on my profile", "Steam gives the first showcase at profile level 10."),
            ],
        },
        "ru": {
            "title": "Как сделать длинную витрину мастерской Steam",
            "description": "Высокая картинка, разрезанная на пять частей мастерской, даёт длинную витрину в профиле Steam. Размеры, лимиты и шаги.",
            "intro": "Steam сохраняет высоту элементов мастерской. Разрежь высокую картинку на пять колонок — и в профиле вместо короткой полосы получится одна длинная иллюстрация вниз по странице.",
            "mode": "workshop",
            "steps": [
                ("Выбери высокую картинку", "Лучше всего подходит вертикальный арт, например 750 × 2000 px. Чем выше картинка, тем длиннее витрина; единственный потолок — 5 МБ на каждую часть."),
                ("Разрежь её на пять частей", "В Showcase Maker выбери «Мастерская» и нажми «Подготовить витрину». Каждая часть — пятая доля ширины во всю высоту картинки."),
                ("Следи за анимированными частями", "У высокого GIF много пикселей в каждом кадре. Каждая часть сама укладывается в 5 МБ; короткая петля на 12–15 кадрах в секунду сохранит качество."),
                ("Загрузи part_1 … part_5 по порядку", "Загружай файлы по одному как элементы мастерской: кодом в консоли из вкладки Steam или расширением SteamShowcase Helper."),
                ("Добавь их в витрину", "«Редактировать профиль» → «Витрина» → «Витрина мастерской», затем отметь пять элементов в том же порядке."),
            ],
            "faq": [
                ("Части сдвинуты или стоят не по порядку", "Выбирай их строго по порядку, первой — part_1. Высота у всех частей одинаковая, поэтому они совпадают только в одном ряду."),
                ("Можно сделать картинку шире?", "Ширину задаёт Steam: около 630 px на весь ряд. Длинная витрина растёт только вниз."),
                ("В профиле нет витрин", "Первую витрину Steam даёт на 10 уровне профиля."),
            ],
        },
        "uk": {
            "title": "Як зробити довгу вітрину майстерні Steam",
            "description": "Висока картинка, розрізана на п’ять частин майстерні, дає довгу вітрину в профілі Steam. Розміри, ліміти й кроки.",
            "intro": "Steam зберігає висоту елементів майстерні. Розріж високу картинку на п’ять колонок — і в профілі замість короткої смуги вийде одна довга ілюстрація вниз сторінкою.",
            "mode": "workshop",
            "steps": [
                ("Обери високу картинку", "Найкраще підходить вертикальний арт, наприклад 750 × 2000 px. Що вища картинка, то довша вітрина; єдина межа — 5 МБ на кожну частину."),
                ("Розріж її на п’ять частин", "У Showcase Maker обери «Майстерня» й натисни «Підготувати вітрину». Кожна частина — п’ята частка ширини на всю висоту картинки."),
                ("Стеж за анімованими частинами", "У високого GIF багато пікселів у кожному кадрі. Кожна частина сама вкладається в 5 МБ; коротка петля на 12–15 кадрах на секунду збереже якість."),
                ("Завантаж part_1 … part_5 по черзі", "Завантажуй файли по одному як елементи майстерні: кодом у консолі з вкладки Steam або розширенням SteamShowcase Helper."),
                ("Додай їх у вітрину", "«Редагувати профіль» → «Вітрина» → «Вітрина майстерні», потім познач п’ять елементів у тому ж порядку."),
            ],
            "faq": [
                ("Частини зсунуті або стоять не по черзі", "Обирай їх строго по черзі, першою — part_1. Висота в усіх частин однакова, тож вони збігаються лише в одному ряду."),
                ("Чи можна зробити картинку ширшою?", "Ширину задає Steam: близько 630 px на весь ряд. Довга вітрина росте лише вниз."),
                ("У профілі немає вітрин", "Першу вітрину Steam дає на 10 рівні профілю."),
            ],
        },
        "de": {
            "title": "So erstellst du eine lange Steam-Workshop-Vitrine",
            "description": "Ein hohes Bild, in fünf Workshop-Teile geschnitten, ergibt eine lange Vitrine im Steam-Profil. Größen, Limits und Schritte.",
            "intro": "Steam behält die Höhe von Workshop-Elementen bei. Schneide ein hohes Bild in fünf Spalten, und dein Profil zeigt statt eines kurzen Streifens ein langes Artwork, das die Seite hinunterläuft.",
            "mode": "workshop",
            "steps": [
                ("Ein hohes Bild wählen", "Hochformat-Art eignet sich am besten, zum Beispiel 750 × 2000 px. Je höher das Bild, desto länger die Vitrine; die einzige Grenze sind 5 MB pro Teil."),
                ("In fünf Teile schneiden", "Wähle in Showcase Maker „Workshop“ und klicke auf „Steam-Dateien erstellen“. Jedes Teil ist ein Fünftel der Breite und behält die volle Höhe des Bildes."),
                ("Auf animierte Teile achten", "Ein hohes GIF hat viele Pixel in jedem Bild. Jedes Teil wird automatisch unter 5 MB gebracht; eine kurze Schleife mit 12–15 Bildern pro Sekunde hält die Qualität hoch."),
                ("part_1 … part_5 der Reihe nach hochladen", "Lade die Dateien einzeln als Workshop-Elemente hoch: mit dem Konsolencode aus dem Steam-Tab oder mit der Erweiterung SteamShowcase Helper."),
                ("Zur Vitrine hinzufügen", "Profil bearbeiten → Vitrine → „Workshop Showcase“ und die fünf Elemente in derselben Reihenfolge auswählen."),
            ],
            "faq": [
                ("Die Teile sind verschoben oder vertauscht", "Wähle sie streng der Reihe nach, part_1 zuerst. Alle Teile sind gleich hoch und passen nur als eine Reihe zusammen."),
                ("Kann ich das Bild breiter machen?", "Die Breite legt Steam fest: etwa 630 px für die ganze Reihe. Lange Vitrinen wachsen nur nach unten."),
                ("In meinem Profil gibt es keine Vitrinen", "Die erste Vitrine gibt Steam ab Profillevel 10."),
            ],
        },
        "tr": {
            "title": "Uzun Steam Atölye vitrini nasıl yapılır",
            "description": "Beş Atölye parçasına kesilen uzun bir resim, Steam profilinde uzun bir vitrin oluşturur. Boyutlar, sınırlar ve adımlar.",
            "intro": "Steam Atölye öğelerinin yüksekliğini korur. Uzun bir resmi beş sütuna kes; profilinde kısa bir şerit yerine sayfa boyunca inen tek uzun bir çizim olur.",
            "mode": "workshop",
            "steps": [
                ("Uzun bir resim seç", "Dikey çizimler en iyisidir, örneğin 750 × 2000 px. Resim ne kadar uzunsa vitrin o kadar uzun olur; tek sınır parça başına 5 MB."),
                ("Beş parçaya kes", "Showcase Maker’da “Atölye”yi seç ve “Steam dosyalarını oluştur”a bas. Her parça genişliğin beşte biridir ve resmin tüm yüksekliğini korur."),
                ("Hareketli parçalara dikkat et", "Uzun bir GIF’in her karesinde çok piksel vardır. Her parça otomatik olarak 5 MB’ın altına sığdırılır; saniyede 12–15 karelik kısa bir döngü kaliteyi yüksek tutar."),
                ("part_1 … part_5’i sırayla yükle", "Dosyaları tek tek Atölye öğesi olarak yükle: Steam sekmesindeki konsol koduyla ya da SteamShowcase Helper eklentisiyle."),
                ("Vitrine ekle", "Profili Düzenle → Vitrin → “Workshop Showcase”, sonra beş öğeyi aynı sırayla seç."),
            ],
            "faq": [
                ("Parçalar kaymış ya da sırası yanlış", "Onları kesinlikle sırayla seç, önce part_1. Tüm parçalar aynı yükseklikte olduğundan yalnızca tek sıra olarak hizalanır."),
                ("Resmi daha geniş yapabilir miyim?", "Genişliği Steam belirler: tüm sıra için yaklaşık 630 px. Uzun vitrinler yalnızca aşağı doğru büyür."),
                ("Profilimde hiç vitrin yok", "Steam ilk vitrini profil seviyesi 10’da verir."),
            ],
        },
        "fr": {
            "title": "Comment créer une vitrine Workshop Steam longue",
            "description": "Une image haute coupée en cinq parties Workshop donne une vitrine longue sur votre profil Steam. Tailles, limites et étapes.",
            "intro": "Steam garde la hauteur des éléments Workshop. Coupez une image haute en cinq colonnes, et votre profil montre une longue illustration qui descend la page au lieu d’une courte bande.",
            "mode": "workshop",
            "steps": [
                ("Choisir une image haute", "Un dessin en portrait marche le mieux, par exemple 750 × 2000 px. Plus l’image est haute, plus la vitrine est longue ; la seule limite est 5 Mo par partie."),
                ("La couper en cinq parties", "Dans Showcase Maker, choisissez « Workshop » et cliquez sur « Créer les fichiers Steam ». Chaque partie fait un cinquième de la largeur et garde toute la hauteur de l’image."),
                ("Surveiller les parties animées", "Un GIF haut a beaucoup de pixels par image. Chaque partie passe automatiquement sous 5 Mo ; une boucle courte à 12–15 images par seconde garde une bonne qualité."),
                ("Envoyer part_1 … part_5 dans l’ordre", "Envoyez les fichiers un par un comme éléments Workshop : avec le code console de l’onglet Steam ou avec l’extension SteamShowcase Helper."),
                ("Les ajouter à la vitrine", "Modifier le profil → Vitrine → « Workshop Showcase », puis sélectionnez les cinq éléments dans le même ordre."),
            ],
            "faq": [
                ("Les parties sont décalées ou dans le désordre", "Sélectionnez-les strictement dans l’ordre, part_1 en premier. Toutes les parties ont la même hauteur et ne s’alignent qu’en une seule rangée."),
                ("Puis-je élargir l’image ?", "La largeur est fixée par Steam : environ 630 px pour toute la rangée. Une vitrine longue ne grandit que vers le bas."),
                ("Je n’ai aucune vitrine sur mon profil", "Steam donne la première vitrine au niveau de profil 10."),
            ],
        },
        "es": {
            "title": "Cómo hacer un escaparate de Workshop largo en Steam",
            "description": "Una imagen alta cortada en cinco partes de Workshop forma un escaparate largo en tu perfil de Steam. Tamaños, límites y pasos.",
            "intro": "Steam conserva la altura de los elementos de Workshop. Corta una imagen alta en cinco columnas y tu perfil mostrará una ilustración larga que baja por la página en lugar de una franja corta.",
            "mode": "workshop",
            "steps": [
                ("Elige una imagen alta", "Lo mejor es un arte vertical, por ejemplo 750 × 2000 px. Cuanto más alta la imagen, más largo el escaparate; el único techo son 5 MB por parte."),
                ("Córtala en cinco partes", "En Showcase Maker elige «Workshop» y pulsa «Crear archivos para Steam». Cada parte es una quinta parte del ancho y conserva toda la altura de la imagen."),
                ("Cuida las partes animadas", "Un GIF alto tiene muchos píxeles en cada fotograma. Cada parte se ajusta sola por debajo de 5 MB; un bucle corto a 12–15 fotogramas por segundo mantiene la calidad."),
                ("Sube part_1 … part_5 en orden", "Sube los archivos uno a uno como elementos de Workshop: con el código de consola de la pestaña Steam o con la extensión SteamShowcase Helper."),
                ("Añádelos al escaparate", "Editar perfil → Escaparate → «Workshop Showcase» y selecciona los cinco elementos en el mismo orden."),
            ],
            "faq": [
                ("Las partes están desplazadas o desordenadas", "Selecciónalas estrictamente en orden, part_1 primero. Todas tienen la misma altura y solo encajan como una fila."),
                ("¿Puedo hacer la imagen más ancha?", "El ancho lo fija Steam: unos 630 px para toda la fila. Un escaparate largo solo crece hacia abajo."),
                ("No tengo escaparates en el perfil", "Steam da el primer escaparate en el nivel de perfil 10."),
            ],
        },
        "pt": {
            "title": "Como fazer uma vitrine longa da Oficina na Steam",
            "description": "Uma imagem alta cortada em cinco partes da Oficina forma uma vitrine longa no seu perfil Steam. Tamanhos, limites e passos.",
            "intro": "A Steam mantém a altura dos itens da Oficina. Corte uma imagem alta em cinco colunas e seu perfil mostra uma ilustração longa descendo pela página em vez de uma faixa curta.",
            "mode": "workshop",
            "steps": [
                ("Escolha uma imagem alta", "Arte vertical funciona melhor, por exemplo 750 × 2000 px. Quanto mais alta a imagem, mais longa a vitrine; o único teto é 5 MB por parte."),
                ("Corte em cinco partes", "No Showcase Maker escolha «Oficina» e clique em «Criar arquivos para a Steam». Cada parte tem um quinto da largura e mantém toda a altura da imagem."),
                ("Cuide das partes animadas", "Um GIF alto tem muitos pixels em cada quadro. Cada parte fica automaticamente abaixo de 5 MB; um loop curto a 12–15 quadros por segundo mantém a qualidade."),
                ("Envie part_1 … part_5 em ordem", "Envie os arquivos um a um como itens da Oficina: com o código de console da aba Steam ou com a extensão SteamShowcase Helper."),
                ("Adicione à vitrine", "Editar perfil → Vitrine → «Workshop Showcase» e selecione os cinco itens na mesma ordem."),
            ],
            "faq": [
                ("As partes estão deslocadas ou fora de ordem", "Selecione estritamente em ordem, part_1 primeiro. Todas têm a mesma altura e só se alinham como uma fileira."),
                ("Posso deixar a imagem mais larga?", "A largura é fixada pela Steam: cerca de 630 px para a fileira inteira. Uma vitrine longa só cresce para baixo."),
                ("Não tenho vitrines no perfil", "A Steam dá a primeira vitrine no nível de perfil 10."),
            ],
        },
    },
}
